import type { CSSProperties, ReactNode } from "react";
import grainUrl from "../assets/grain.svg";
import foldLitUrl from "../assets/skin-fold-lit.svg";
import foldDarkUrl from "../assets/skin-fold-dark.svg";
import { TORN_STRIP_WIDTH, tornEdgePlan } from "./torn";

// The rim bands and the paper's own surface carry the skin's crumple: the
// same paired zero-mean fold layers the body uses (01 §2 L0 amended) — the
// black stock is one continuous material, so its cut face is textured too.

import edgeTop1 from "../assets/torn/edge-top-1.png";
import edgeTop2 from "../assets/torn/edge-top-2.png";
import edgeTop3 from "../assets/torn/edge-top-3.png";
import edgeBottom1 from "../assets/torn/edge-bottom-1.png";
import edgeBottom2 from "../assets/torn/edge-bottom-2.png";
import edgeBottom3 from "../assets/torn/edge-bottom-3.png";

// TornSheet — the L2 shared primitive, v3 (01 §2 L2): light paper revealed
// where the matte black skin tears away. The black layer's own ragged rim is
// the fringe (dark framing light, per the placement ruling); text padding is
// computed from --fringe-w so text never sits under it (gate 3).
//
// v3 changes HOW the tear is cut, not what it means. v2 used a clip-path
// polygon with random vertices, which reads as a sawtooth at any vertex
// count: paper does not separate in straight segments, it separates along
// its fibres. The edge is now a raster alpha mask generated by
// `scripts/gen_torn_edges.py` — multi-octave, frayed, with strands pulled
// proud of the tear — tiled horizontally so a sheet's height never stretches
// its edge.
//
// Everything stays STATIC: the variant and offset are a pure function of the
// sheet's seed, so a sheet always tears the same way and nothing is decided
// at paint time (gate 4). Shadow is flat — torn paper never glows.

const EDGE_TOP = [edgeTop1, edgeTop2, edgeTop3];
const EDGE_BOTTOM = [edgeBottom1, edgeBottom2, edgeBottom3];

// The generator writes 1600x160 strips, rendered at 50%: an 80px band whose
// tear swings 20-30px vertically, matching the reference, where the black
// band's thickness varies enormously across the width. Downscaling only
// sharpens the fine serration.
const STRIP_SCALE = 0.5;

/** Rendered height of one edge strip, px. */
const EDGE_H = Math.round(160 * STRIP_SCALE);

/** Rendered tiling period, px — scaled with the height so the tear keeps shape. */
const EDGE_W = Math.round(TORN_STRIP_WIDTH * STRIP_SCALE);

/**
 * The torn cross-section of the skin, outermost first. Thick stock shows
 * its own thickness along a tear — a bright narrow cut face against the
 * paper, falling into the dark body within about 6px. Measured off the
 * reference (luminance 72 at 2px, 41 at 4px, 17 at 6px), approximated here
 * as graded bands cut by the SAME tear, so the cross-section follows every
 * serration instead of outlining it.
 */
const RIM_BANDS: ReadonlyArray<{ inset: number; color: string }> = [
  { inset: 8, color: "var(--bg)" },
  { inset: 6, color: "var(--skin-lip-3)" },
  { inset: 4, color: "var(--skin-lip-2)" },
  { inset: 2, color: "var(--skin-lip-1)" },
];


/** The paper tints (01 §1 + 2026-10-10 amendment) — taxonomy, never valence. */
export type TornSheetTint =
  "cream" | "mint" | "sky" | "blush" | "butter" | "violet";

const TINT_TOKEN: Record<TornSheetTint, string> = {
  cream: "var(--paper-cream)",
  mint: "var(--paper-mint)",
  sky: "var(--paper-sky)",
  blush: "var(--paper-blush)",
  butter: "var(--paper-butter)",
  violet: "var(--paper-violet)",
};

/** Accent left-rule, optional (mockup: teal on the plan sheet). */
export type TornRule = "accent-1" | "accent-2";

const RULE_TOKEN: Record<TornRule, string> = {
  "accent-1": "var(--accent-1)",
  "accent-2": "var(--accent-2)",
};

/**
 * The sheet's own torn face catching light, per tint (mockup 2026-10-10):
 * white stock core on the warm papers, and on violet the bright violet glow
 * the reference carries along the whole tear.
 */
const LIP_TOKEN: Record<TornSheetTint, string> = {
  cream: "rgba(255, 255, 255, 0.42)",
  mint: "rgba(255, 255, 255, 0.5)",
  sky: "rgba(255, 255, 255, 0.5)",
  blush: "rgba(255, 255, 255, 0.55)",
  butter: "rgba(255, 255, 255, 0.5)",
  violet: "var(--accent-2)",
};

export interface TornSheetProps {
  /** Paper tint, selecting one of the paper tokens from theme.css. */
  tint?: TornSheetTint;
  /** Deterministic tear shape; same seed, same tear, every render. */
  seed?: string;
  /** Optional accent left-rule (hue law: teal you-act, plum agents-act). */
  rule?: TornRule;
  /**
   * Ragged fringe width, exposed to the sheet as the --fringe-w custom
   * property (defaults to the :root value). Text padding is computed from
   * it — the fringe exclusion zone (gate 3) — so text can never sit under
   * the fringe, whatever width the caller sets.
   */
  fringeWidth?: string;
  /** Static rotation in degrees; clamped to the 1deg ceiling (01 §2 L2). */
  rotationDeg?: number;
  className?: string;
  children: ReactNode;
}

/** Build the layered CSS mask: torn strip at the top, solid middle, torn strip
 * at the bottom. Listed top-to-bottom; `mask-size` keeps the middle exactly
 * the leftover height, so the edges never scale with the sheet.
 */
function maskLayers(
  top: string,
  bottom: string,
  topOffset: number,
  bottomOffset: number,
): CSSProperties {
  const solid = "linear-gradient(#000, #000)";
  return {
    maskImage: `url(${top}), ${solid}, url(${bottom})`,
    WebkitMaskImage: `url(${top}), ${solid}, url(${bottom})`,
    maskRepeat: "repeat-x, no-repeat, repeat-x",
    WebkitMaskRepeat: "repeat-x, no-repeat, repeat-x",
    maskSize: `${EDGE_W}px ${EDGE_H}px, 100% calc(100% - ${EDGE_H * 2}px), ${EDGE_W}px ${EDGE_H}px`,
    WebkitMaskSize: `${EDGE_W}px ${EDGE_H}px, 100% calc(100% - ${EDGE_H * 2}px), ${EDGE_W}px ${EDGE_H}px`,
    maskPosition: `${-topOffset}px top, left ${EDGE_H}px, ${-bottomOffset}px bottom`,
    WebkitMaskPosition: `${-topOffset}px top, left ${EDGE_H}px, ${-bottomOffset}px bottom`,
  } as CSSProperties;
}

/** Offsets are picked against the strip's own width; scale them to match. */
function scaleOffset(offset: number): number {
  return Math.round(offset * STRIP_SCALE);
}

export function TornSheet({
  tint = "cream",
  seed = "eudaimonia",
  rule,
  fringeWidth,
  rotationDeg = -0.4,
  className,
  children,
}: TornSheetProps) {
  const rotation = Math.max(-1, Math.min(1, rotationDeg));
  const plan = tornEdgePlan(seed);
  const topSrc = EDGE_TOP[plan.topVariant - 1];
  const bottomSrc = EDGE_BOTTOM[plan.bottomVariant - 1];

  const outerStyle = {
    ...(fringeWidth === undefined ? {} : { "--fringe-w": fringeWidth }),
    position: "relative",
    transform: `rotate(${rotation}deg)`,
    // Only a slight seat under the whole sheet. The depth at the tear comes
    // from the skin falling INWARD onto the paper (see skinCast below), not
    // from the paper casting outward — the skin is the top layer.
    filter: "drop-shadow(var(--sheet-seat))",
  } as CSSProperties;

  // The skin's own torn rim, cut by the same tear a few pixels proud of the
  // paper. Painted in --skin-lip rather than the flat base: in the
  // reference the black's cut edge curls and catches light, and without
  // that the tear reads as a shape stamped out of a flat field rather than
  // as a layer torn away (placement ruling, 01 §2).
  // Each band's box is `inset` px wider than the paper's, and mask-position
  // is measured from that box's own origin — so without compensation every
  // band tiles the tear at a slightly different horizontal phase and the
  // serrations stop lining up. Four misaligned copies read as a grey haze
  // instead of a cut face. Adding the inset back puts every band on the
  // same absolute phase, so the cross-section steps cleanly.
  const rimStyle = (inset: number, color: string): CSSProperties => ({
    position: "absolute",
    inset: `${-inset}px`,
    // The cut face is black stock — it carries the skin's crumple too, not
    // a flat fill (same paired folds the body wears, 01 §2 L0 amended).
    backgroundImage: `url(${foldLitUrl}), url(${foldDarkUrl})`,
    backgroundColor: color,
    pointerEvents: "none",
    ...maskLayers(
      topSrc,
      bottomSrc,
      scaleOffset(plan.topOffset) + inset,
      scaleOffset(plan.bottomOffset) + inset,
    ),
  });

  // The paper sits inside the fringe's box by RIM on every side, cut by the
  // SAME tear — so the few pixels of difference are a dark ragged rim that
  // follows the tear exactly, rather than an outline drawn around it.
  // The skin's torn edge falling onto the paper below it. Clipped by the
  // paper's own mask (overflow hidden + the mask), so the cast follows the
  // tear instead of running straight across.
  // Stops trace the measured falloff (theme.css --skin-cast-*): steep for
  // the first few pixels, then a long thin tail. A single linear ramp reads
  // as a gradient laid over the paper; this reads as a shadow.
  const skinCast = (edge: "top" | "bottom"): CSSProperties => ({
    position: "absolute",
    left: 0,
    right: 0,
    [edge]: 0,
    height: "var(--skin-cast-depth)",
    background: `linear-gradient(${edge === "top" ? 180 : 0}deg, var(--skin-cast-max) 0%, var(--skin-cast-mid) 14%, var(--skin-cast-far) 36%, transparent 100%)`,
    pointerEvents: "none",
  });

  // The sheet's torn faces catching light, per tint (mockup 2026-10-10):
  // the TOP tear shows the white stock core fading into the tint's glow —
  // bright violet on agents — and the BOTTOM tear tears DARK, the sheet's
  // underside merging into the black band. Both masked by the same strips
  // their edges use, so they follow every serration.
  const topLipStyle: CSSProperties = {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: `${EDGE_H}px`,
    background: `linear-gradient(180deg, rgba(255,255,255,0.85) 0%, ${LIP_TOKEN[tint]} 30%, transparent 60%)`,
    pointerEvents: "none",
    maskImage: `url(${topSrc})`,
    WebkitMaskImage: `url(${topSrc})`,
    maskRepeat: "repeat-x",
    WebkitMaskRepeat: "repeat-x",
    maskSize: `${EDGE_W}px ${EDGE_H}px`,
    WebkitMaskSize: `${EDGE_W}px ${EDGE_H}px`,
    maskPosition: `${-scaleOffset(plan.topOffset)}px top`,
    WebkitMaskPosition: `${-scaleOffset(plan.topOffset)}px top`,
  };

  const bottomLipStyle: CSSProperties = {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: `${EDGE_H}px`,
    background: `linear-gradient(0deg, var(--skin-lip-3) 0%, var(--skin-lip-2) 22%, transparent 58%)`,
    pointerEvents: "none",
    maskImage: `url(${bottomSrc})`,
    WebkitMaskImage: `url(${bottomSrc})`,
    maskRepeat: "repeat-x",
    WebkitMaskRepeat: "repeat-x",
    maskSize: `${EDGE_W}px ${EDGE_H}px`,
    WebkitMaskSize: `${EDGE_W}px ${EDGE_H}px`,
    maskPosition: `${-scaleOffset(plan.bottomOffset)}px bottom`,
    WebkitMaskPosition: `${-scaleOffset(plan.bottomOffset)}px bottom`,
  };

  const paperStyle: CSSProperties = {
    position: "relative",
    background: TINT_TOKEN[tint],
    color: "var(--paper-ink)",
    // The tear bites into the sheet, so content clears it vertically as
    // well as clearing the fringe horizontally (gate 3).
    paddingTop: `calc(var(--fringe-w) * 0.55 + ${EDGE_H}px)`,
    paddingBottom: `calc(var(--fringe-w) * 0.55 + ${EDGE_H}px)`,
    paddingLeft: "calc(var(--fringe-w) * 1.5)",
    paddingRight: "calc(var(--fringe-w) * 1.5)",
    overflow: "hidden",
    ...maskLayers(topSrc, bottomSrc, scaleOffset(plan.topOffset), scaleOffset(plan.bottomOffset)),
  };

  return (
    <section className={className} style={outerStyle}>
      {RIM_BANDS.map((band) => (
        <span key={band.inset} aria-hidden="true" style={rimStyle(band.inset, band.color)} />
      ))}
      <div style={paperStyle}>
        <span aria-hidden="true" style={skinCast("top")} />
        <span aria-hidden="true" style={skinCast("bottom")} />
        <span aria-hidden="true" style={topLipStyle} />
        <span aria-hidden="true" style={bottomLipStyle} />
        <span aria-hidden="true" style={topLipStyle} />
        {rule !== undefined ? (
          <span
            aria-hidden="true"
            style={{
              position: "absolute",
              left: 0,
              top: `${EDGE_H * 0.4}px`,
              bottom: `${EDGE_H * 0.4}px`,
              width: "3px",
              background: RULE_TOKEN[rule],
            }}
          />
        ) : null}
        {/* Paper surface: fiber striations + crumple mottling + a lit top
              edge, all static and faint — texture reads as paper tooth and
              crumple (gate 4: never moves). */}
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url(${foldDarkUrl})`,
            opacity: 0.05,
            pointerEvents: "none",
          }}
        />
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url(${foldLitUrl})`,
            opacity: 0.04,
            pointerEvents: "none",
          }}
        />
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            background:
              "linear-gradient(180deg, rgba(255,255,255,0.16), rgba(255,255,255,0) 22%)",
            pointerEvents: "none",
          }}
        />
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url(${grainUrl})`,
            opacity: 0.015,
            pointerEvents: "none",
          }}
        />
        <div style={{ position: "relative" }}>{children}</div>
      </div>
    </section>
  );
}
