import type { CSSProperties, ReactNode } from "react";
import grainUrl from "../assets/grain.svg";
import { TORN_STRIP_WIDTH, tornEdgePlan } from "./torn";

import edgeTop1 from "../assets/torn/edge-top-1.png";
import edgeTop2 from "../assets/torn/edge-top-2.png";
import edgeTop3 from "../assets/torn/edge-top-3.png";
import edgeBottom1 from "../assets/torn/edge-bottom-1.png";
import edgeBottom2 from "../assets/torn/edge-bottom-2.png";
import edgeBottom3 from "../assets/torn/edge-bottom-3.png";

// TornSheet — the L2 shared primitive, v3 (01 §2 L2): light paper revealed
// where the matte black skin tears away. The black layer's own ragged rim is
// the fringe (dark framing light, per the placement ruling); text padding is
// computed from --fringe-w so text never sits under it (gate 3).
//
// v3 changes HOW the tear is cut, not what it means. v2 used a clip-path
// polygon with random vertices, which reads as a sawtooth at any vertex
// count: paper does not separate in straight segments, it separates along
// its fibres. The edge is now a raster alpha mask generated by
// `scripts/gen_torn_edges.py` — multi-octave, frayed, with strands pulled
// proud of the tear — tiled horizontally so a sheet's height never stretches
// its edge.
//
// Everything stays STATIC: the variant and offset are a pure function of the
// sheet's seed, so a sheet always tears the same way and nothing is decided
// at paint time (gate 4). Shadow is flat — torn paper never glows.

const EDGE_TOP = [edgeTop1, edgeTop2, edgeTop3];
const EDGE_BOTTOM = [edgeBottom1, edgeBottom2, edgeBottom3];

// The generator writes 1600x96 strips. They render at 45% so the tear
// reads at a phone's scale — about 43px of bite rather than 96px, which
// swallowed short sheets whole — and downscaling only sharpens the detail.
const STRIP_SCALE = 0.45;

/** Rendered height of one edge strip, px. */
const EDGE_H = Math.round(96 * STRIP_SCALE);

/** Rendered tiling period, px — scaled with the height so the tear keeps shape. */
const EDGE_W = Math.round(TORN_STRIP_WIDTH * STRIP_SCALE);

/** How far the skin's rim sits proud of the paper, px. */
const RIM = 4;

/** How far the pale fibre core sits proud of the paper, px — inside the rim. */
const CORE = 2;

/** The paper tints (01 §1 + 2026-10-10 amendment) — taxonomy, never valence. */
export type TornSheetTint =
  "cream" | "mint" | "sky" | "blush" | "butter" | "violet";

const TINT_TOKEN: Record<TornSheetTint, string> = {
  cream: "var(--paper-cream)",
  mint: "var(--paper-mint)",
  sky: "var(--paper-sky)",
  blush: "var(--paper-blush)",
  butter: "var(--paper-butter)",
  violet: "var(--paper-violet)",
};

/** Accent left-rule, optional (mockup: teal on the plan sheet). */
export type TornRule = "accent-1" | "accent-2";

const RULE_TOKEN: Record<TornRule, string> = {
  "accent-1": "var(--accent-1)",
  "accent-2": "var(--accent-2)",
};

export interface TornSheetProps {
  /** Paper tint, selecting one of the paper tokens from theme.css. */
  tint?: TornSheetTint;
  /** Deterministic tear shape; same seed, same tear, every render. */
  seed?: string;
  /** Optional accent left-rule (hue law: teal you-act, plum agents-act). */
  rule?: TornRule;
  /**
   * Ragged fringe width, exposed to the sheet as the --fringe-w custom
   * property (defaults to the :root value). Text padding is computed from
   * it — the fringe exclusion zone (gate 3) — so text can never sit under
   * the fringe, whatever width the caller sets.
   */
  fringeWidth?: string;
  /** Static rotation in degrees; clamped to the 1deg ceiling (01 §2 L2). */
  rotationDeg?: number;
  className?: string;
  children: ReactNode;
}

/**
 * Build the layered CSS mask: torn strip at the top, solid middle, torn strip
 * at the bottom. Listed top-to-bottom; `mask-size` keeps the middle exactly
 * the leftover height, so the edges never scale with the sheet.
 */
function maskLayers(
  top: string,
  bottom: string,
  topOffset: number,
  bottomOffset: number,
): CSSProperties {
  const solid = "linear-gradient(#000, #000)";
  return {
    maskImage: `url(${top}), ${solid}, url(${bottom})`,
    WebkitMaskImage: `url(${top}), ${solid}, url(${bottom})`,
    maskRepeat: "repeat-x, no-repeat, repeat-x",
    WebkitMaskRepeat: "repeat-x, no-repeat, repeat-x",
    maskSize: `${EDGE_W}px ${EDGE_H}px, 100% calc(100% - ${EDGE_H * 2}px), ${EDGE_W}px ${EDGE_H}px`,
    WebkitMaskSize: `${EDGE_W}px ${EDGE_H}px, 100% calc(100% - ${EDGE_H * 2}px), ${EDGE_W}px ${EDGE_H}px`,
    maskPosition: `${-topOffset}px top, left ${EDGE_H}px, ${-bottomOffset}px bottom`,
    WebkitMaskPosition: `${-topOffset}px top, left ${EDGE_H}px, ${-bottomOffset}px bottom`,
  } as CSSProperties;
}

/** Offsets are picked against the strip's own width; scale them to match. */
function scaleOffset(offset: number): number {
  return Math.round(offset * STRIP_SCALE);
}

export function TornSheet({
  tint = "cream",
  seed = "eudaimonia",
  rule,
  fringeWidth,
  rotationDeg = -0.4,
  className,
  children,
}: TornSheetProps) {
  const rotation = Math.max(-1, Math.min(1, rotationDeg));
  const plan = tornEdgePlan(seed);
  const topSrc = EDGE_TOP[plan.topVariant - 1];
  const bottomSrc = EDGE_BOTTOM[plan.bottomVariant - 1];

  const outerStyle = {
    ...(fringeWidth === undefined ? {} : { "--fringe-w": fringeWidth }),
    position: "relative",
    transform: `rotate(${rotation}deg)`,
    // Only a slight seat under the whole sheet. The depth at the tear comes
    // from the skin falling INWARD onto the paper (see skinCast below), not
    // from the paper casting outward — the skin is the top layer.
    filter: "drop-shadow(var(--sheet-seat))",
  } as CSSProperties;

  // The fringe: the black skin's own torn rim. Same masks, offset by a few
  // pixels and painted in the base, so a dark ragged rim frames the light
  // paper rather than the paper floating on black (placement ruling, 01 §2).
  const fringeStyle: CSSProperties = {
    position: "absolute",
    inset: `${-RIM}px`,
    background: "var(--bg)",
    pointerEvents: "none",
    ...maskLayers(topSrc, bottomSrc, scaleOffset(plan.topOffset), scaleOffset(plan.bottomOffset)),
  };

  // The paper sits inside the fringe's box by RIM on every side, cut by the
  // SAME tear — so the few pixels of difference are a dark ragged rim that
  // follows the tear exactly, rather than an outline drawn around it.
  // The pale fibre core: torn coloured stock is white inside, and that thin
  // bright line along the tear is most of what makes paper read as torn
  // rather than as a shape with a ragged outline. It sits between the skin's
  // rim and the paper, cut by the same tear.
  const coreStyle: CSSProperties = {
    position: "absolute",
    inset: `${-CORE}px`,
    background: "var(--paper-core)",
    pointerEvents: "none",
    ...maskLayers(topSrc, bottomSrc, scaleOffset(plan.topOffset), scaleOffset(plan.bottomOffset)),
  };

  // The skin's torn edge falling onto the paper below it. Clipped by the
  // paper's own mask (overflow hidden + the mask), so the cast follows the
  // tear instead of running straight across.
  const skinCast = (edge: "top" | "bottom"): CSSProperties => ({
    position: "absolute",
    left: 0,
    right: 0,
    [edge]: 0,
    height: `${Math.round(EDGE_H * 1.15)}px`,
    background: `linear-gradient(${edge === "top" ? 180 : 0}deg, var(--skin-cast), transparent)`,
    pointerEvents: "none",
  });

  const paperStyle: CSSProperties = {
    position: "relative",
    background: TINT_TOKEN[tint],
    color: "var(--paper-ink)",
    // The tear bites into the sheet, so content clears it vertically as
    // well as clearing the fringe horizontally (gate 3).
    paddingTop: `calc(var(--fringe-w) * 0.55 + ${EDGE_H}px)`,
    paddingBottom: `calc(var(--fringe-w) * 0.55 + ${EDGE_H}px)`,
    paddingLeft: "calc(var(--fringe-w) * 1.5)",
    paddingRight: "calc(var(--fringe-w) * 1.5)",
    overflow: "hidden",
    ...maskLayers(topSrc, bottomSrc, scaleOffset(plan.topOffset), scaleOffset(plan.bottomOffset)),
  };

  return (
    <section className={className} style={outerStyle}>
      <span aria-hidden="true" style={fringeStyle} />
      <span aria-hidden="true" style={coreStyle} />
      <div style={paperStyle}>
        <span aria-hidden="true" style={skinCast("top")} />
        <span aria-hidden="true" style={skinCast("bottom")} />
        {rule !== undefined ? (
          <span
            aria-hidden="true"
            style={{
              position: "absolute",
              left: 0,
              top: `${EDGE_H * 0.4}px`,
              bottom: `${EDGE_H * 0.4}px`,
              width: "3px",
              background: RULE_TOKEN[rule],
            }}
          />
        ) : null}
        {/* Paper surface: fiber striations + a lit top edge, both static
              and faint — texture reads as paper tooth (gate 4: never moves). */}
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage:
              "repeating-linear-gradient(105deg, rgba(43,41,38,0.05) 0px, rgba(43,41,38,0.05) 1px, transparent 1px, transparent 4px)",
            pointerEvents: "none",
          }}
        />
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            background:
              "linear-gradient(180deg, rgba(255,255,255,0.16), rgba(255,255,255,0) 22%)",
            pointerEvents: "none",
          }}
        />
        <span
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url(${grainUrl})`,
            opacity: 0.015,
            pointerEvents: "none",
          }}
        />
        <div style={{ position: "relative" }}>{children}</div>
      </div>
    </section>
  );
}
